# Generated by Django 5.1.4 on 2025-01-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_estima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=20)),
                ('calorie', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='url',
            name='description',
            field=models.CharField(default='opis', max_length=2000),
        ),
        migrations.AddField(
            model_name='url',
            name='ingredients',
            field=models.CharField(default='skladniki', max_length=200),
        ),
        migrations.AddField(
            model_name='url',
            name='recipe_header',
            field=models.CharField(default='Tytul Przepisu', max_length=50),
        ),
        migrations.AddField(
            model_name='url',
            name='calorie',
            field=models.ManyToManyField(to='recipe_estima.calorie'),
        ),
    ]
