# Generated by Django 5.1.4 on 2025-01-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_estima', '0003_initial_calories_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calorie',
            name='ingredient',
            field=models.CharField(max_length=100),
        ),
    ]
